---
title: "Siegle_Hw1"
author: "Aaron_Siegle"
date: "2026-09-01"
output: html_document
---

```{r}
# Reading in the data 
install.packages('R.utils')
install.packages("viridis")
library(sf)
library(data.table)
library(viridis)
library(R.utils)
```

```{r}
# Reading in using data.table 
crops <- fread("qs.crops_20170829.txt.gz")
```

```{r}
# Exploring the data 
crops[, range("YEAR0")]
```

```{r}
names(crops)
```

```{r}
crops[, unique(COMMODITY_DESC)]
```

```{r}
crops[COMMODITY_DESC == "CORN"] 
```

```{r}
crops[COMMODITY_DESC == "CORN", .N, by=SHORT_DESC][order(-N)] 
```

```{r}
crops[SHORT_DESC == "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE", .N, by=.(YEAR, COUNTY_NAME, STATE_NAME)]
```

```{r}
crops[SHORT_DESC == "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE", .N, by=.(YEAR, COUNTY_NAME, STATE_NAME)][order(-N)] 
```
```{r}
print(crops$COUNTY_ANSI)
```
```{r}
print(crops$STATE_ANSI)
```


```{r}
crops[SHORT_DESC == "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE" & AGG_LEVEL_DESC == "COUNTY" & STATE_NAME == "TEXAS" & YEAR == 1987]
```



```{r}
crops[SHORT_DESC == "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE" & AGG_LEVEL_DESC == "COUNTY", .N, STATE_NAME][order(-N)]
```


```{r}
#Q1: What US county has recorded the highest average corn yield since 1990?
crops[SHORT_DESC == "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE" & AGG_LEVEL_DESC == "COUNTY" & YEAR >= 1990, .(avg_yield = mean(as.numeric(VALUE), na.rm = TRUE)), by = .(STATE_NAME, COUNTY_NAME)][order(-avg_yield)]
# The county with the highest average corn yield since 1990 is Benton County, Washington with an average corn yield of 225.84 Bushels per acre. 
```


```{r}
#Q2: What is the highest reported annual corn yield? In what county?
crops[SHORT_DESC == "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE" & AGG_LEVEL_DESC == "COUNTY", .(max_yield = max(as.numeric(VALUE), na.rm = TRUE)), by = .(STATE_NAME, COUNTY_NAME, YEAR)][order(-max_yield)]
# The highest reported annual corn yield was in 2016 in Sutter County, California with a yield of 264.1 bushels per acre. 
```

```{r}
crops[COMMODITY_DESC == "SOYBEANS"] 
```
```{r}
crops[COMMODITY_DESC == "SOYBEANS", .N, by=SHORT_DESC][order(-N)]
```
```{r}
crops[SHORT_DESC == "SOYBEANS - ACRES PLANTED" & YEAR == 2014, .N, by=.(YEAR, STATE_NAME)]
```
```{r}
crops[SHORT_DESC == "SOYBEANS - ACRES PLANTED" & YEAR == 2014, .N, by=.(YEAR, STATE_NAME)][order(-N)]
```

```{r}
crops[SHORT_DESC == "SOYBEANS - ACRES PLANTED" & AGG_LEVEL_DESC == "COUNTY" & STATE_NAME == "IOWA" & YEAR == 2014]
```
```{r}
crops[SHORT_DESC == "SOYBEANS - ACRES PLANTED" & AGG_LEVEL_DESC == "COUNTY", .N, STATE_NAME][order(-N)]
```
 


```{r}
#Q3: What state has the most acres of soy in 2014?
# I'm not entirely sure how to deal with the D values but I want to make sure that counties with D values are included in the state total 
crops[SHORT_DESC == "SOYBEANS - ACRES PLANTED" & YEAR == 2014 & AGG_LEVEL_DESC == "COUNTY", .(soy_acres = sum(as.numeric(gsub(",","",ifelse(VALUE == "(D)", "0", VALUE))), na.rm = TRUE)), by=.(STATE_NAME)][order(-soy_acres)]
# Iowa had the most acres of soy planted in 2014, with 9.85 million acres planted. 
```

```{r}
# Reading in the shapefile 
county <- st_read("/vsizip/cb_2015_us_county_20m (2).zip/cb_2015_us_county_20m/cb_2015_us_county_20m.shp")
```


```{r}
names(county)
```
```{r}
head(county)
```
```{r}
county$FIPS <- paste(county$STATEFP, county$COUNTYFP, sep = "")
print(county$FIPS)
```


```{r}
crops$FIPS <- paste(crops$STATE_ANSI, crops$COUNTY_ANSI, sep = "")
print(crops$FIPS)
```


```{r}
# Merge the crops dataset with the county dataset
county_crops <- merge(county, crops, by="FIPS", all.x=TRUE, all.y=TRUE)
print(county_crops$FIPS)
```
```{r}
# This takes a long time to run 
class(county_crops)
county_crops <- as.data.table(county_crops)
```
```{r}
# Convert to numeric
county_crops[, VALUE := as.numeric(gsub(",","",ifelse(VALUE == "(D)", "0", VALUE)))]
```


```{r}
#Q4: What state has the highest average land fraction used for soy production since 1990?
county_crops[SHORT_DESC == "SOYBEANS - ACRES PLANTED" & YEAR >= 1990, .(avg_frac_soy = mean(VALUE/as.numeric(ALAND), na.rm = TRUE)), by=.(STATE_NAME)][order(-avg_frac_soy)]
# Illinois has the highest average land fraction used for soy since 1990 at 6.78x10^-5. 
```


```{r}
# Test map 
plot(county)
```

```{r}
# Need to remember that county crops is now a data table, so I will still need to convert back to an sf for it to be spatial 
corn_yield_map <- crops[SHORT_DESC == "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE" & AGG_LEVEL_DESC == "COUNTY" & YEAR >= 1990, .(avg_yield = mean(as.numeric(gsub(",", "", VALUE)), na.rm = TRUE)), by = .(STATE_NAME, COUNTY_NAME, FIPS)]
print(corn_yield_map)
```

```{r}
#Q5: Map 1: county average corn yield since 1990
library(viridis)
plot(corn_yield_map_projected["avg_yield"], pal = viridis, breaks="jenks", key.pos=4, axes=T, main="County Average Corn Yield Since 1990 (BU/Acre)", xlim = c(-125, -66), ylim = c(24, 50))
```

```{r}
# Finding the most recent year in the NASS Data
crops[, unique(YEAR)]
```
```{r}
# Isolating the 2018 corn yield value
corn_yield_2018 <- crops[SHORT_DESC == "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE" & AGG_LEVEL_DESC == "COUNTY" & YEAR == 2018, .(STATE_NAME, COUNTY_NAME, VALUE)]
print(corn_yield_2018)
```

```{r}
# Isolating the 1990 corn yield value 

```

```{r}
# Finding the county level increase in corn yield 
```


```{r}
#Q5: Map 2: county rate of corn yield increase (slope of trend since 1990)
```

